import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateBillPDF({ month, totalMessCost, totalMessMeals, mealRate, bills }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Header ──
  doc.setFillColor(29, 78, 216);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text("Bachelor's Wallet", pageWidth / 2, 18, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Mess Finance & Management System', pageWidth / 2, 28, { align: 'center' });

  doc.setFontSize(10);
  doc.text(`Monthly Bill — ${month}`, pageWidth / 2, 36, { align: 'center' });

  // ── Summary Cards ──
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 52);

  const summaryData = [
    ['Total Mess Cost', `BDT ${totalMessCost}`,
     'Total Meals', `${totalMessMeals} meals`],
    ['Meal Rate', `BDT ${mealRate} / meal`,
     'Total Members', `${bills.length} members`],
  ];

  autoTable(doc, {
    startY: 56,
    body: summaryData,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [239, 246, 255], textColor: [29, 78, 216] },
      1: { fillColor: [249, 250, 251] },
      2: { fontStyle: 'bold', fillColor: [239, 246, 255], textColor: [29, 78, 216] },
      3: { fillColor: [249, 250, 251] },
    },
  });

  // ── Bill Table ──
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Member-wise Bill', 14, finalY);

  const tableRows = bills.map((b, i) => [
    i + 1,
    b.name || '-',
    b.room || '-',
    b.totalMeals,
    `BDT ${mealRate}`,
    `BDT ${b.totalBill}`,
    b.paid ? 'Paid' : 'Due',
  ]);

  autoTable(doc, {
    startY: finalY + 4,
    head: [['#', 'Name', 'Room', 'Meals', 'Rate', 'Bill', 'Status']],
    body: tableRows,
    theme: 'striped',
    headStyles: {
      fillColor: [29, 78, 216],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: { fontSize: 10 },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      3: { halign: 'center' },
      4: { halign: 'center' },
      5: { halign: 'center', fontStyle: 'bold' },
      6: {
        halign: 'center',
        fontStyle: 'bold',
      },
    },
    didDrawCell(data) {
      if (data.column.index === 6 && data.section === 'body') {
        const val = data.cell.raw;
        if (val === 'Paid') {
          doc.setTextColor(21, 128, 61);
        } else {
          doc.setTextColor(220, 38, 38);
        }
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(val, data.cell.x + data.cell.width / 2,
          data.cell.y + data.cell.height / 2 + 1, { align: 'center' });
        doc.setTextColor(0, 0, 0);
      }
    },
  });

  // ── Total Row ──
  const totalY = doc.lastAutoTable.finalY + 8;
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(14, totalY, pageWidth - 28, 14, 3, 3, 'F');
  doc.setTextColor(29, 78, 216);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Mess Expenditure: BDT ${totalMessCost}`, pageWidth / 2, totalY + 9.5, { align: 'center' });

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 14;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, footerY - 4, pageWidth - 14, footerY - 4);
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text("Generated by Bachelor's Wallet — Smart Mess Finance Manager", pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB')}`, pageWidth / 2, footerY + 5, { align: 'center' });

  // ── Save ──
  doc.save(`bachelors-wallet-bill-${month}.pdf`);
}